name: E2E MLOps Pipeline
on:
  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run all steps including model training and deployment'
        required: false
        default: 'true'
        type: boolean
      run_data_processing:
        description: 'Run data processing job'
        required: false
        default: 'false'
        type: boolean
      run_feature_engineering:
        description: 'Run feature engineering job'
        required: false
        default: 'false'
        type: boolean
      run_model_training:
        description: 'Run model training job'
        required: false
        default: 'false'
        type: boolean
      run_build_and_push:
        description: 'Run Docker build and push job'
        required: false
        default: 'false'
        type: boolean
  release:
    types: [created]
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  data-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process Data
        run: |
          python src/data/run_processing.py   --input data/raw/house_data.csv   --output data/processed/cleaned_house_data.csv

      - name: Engineer Features
        run: |
          python src/features/engineer.py   --input data/processed/cleaned_house_data.csv   --output data/processed/featured_house_data.csv   --preprocessor models/trained/preprocessor.pkl

      - name: Upload Processed Data Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-data    
          path: data/processed/featured_house_data.csv

      - name: Upload Preprocessor Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessor    
          path: models/trained/preprocessor.pkl

  model-training:
    needs: data-processing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          cache: 'pip'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Processed Data Artifact
        uses: actions/download-artifact@v4
        with:
          name: processed-data           
          path: data/processed

      - name: Setup MLFlow Tracking Server
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlflow-tracking-server ghcr.io/mlflow/mlflow:latest mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /tmp/mlruns

      - name: Wait for MLFlow Server to be Ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5555/health; then
              echo "MLFlow server is up!"
              break
            else
              echo "Waiting for MLFlow server..."
              sleep 5
            fi
          done


      - name: Train Model
        run: |
          mkdir -p models
          python src/models/train_model.py   --config configs/model_config.yaml   --data data/processed/featured_house_data.csv   --models-dir models  --mlflow-tracking-uri http://localhost:5555

      - name: Upload Trained Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/

      - name: Teardown MLFlow Tracking Server
        run: |
          docker stop mlflow-tracking-server
          docker rm mlflow-tracking-server
          docker rmi ghcr.io/mlflow/mlflow:latest

  build-and-publish:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Trained Model Artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model 
          path: models/

      - name: Download Preprocessor Artifact
        uses: actions/download-artifact@v4
        with:
          name: preprocessor      
          path: models/trained/

    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Test Docker image
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ${{vars.DOCKERHUB_USERNAME}}/house-predicter-api:$COMMIT_HASH -f Dockerfile .
          docker build -t ${{vars.DOCKERHUB_USERNAME}}/streamlitapp:$COMMIT_HASH -f streamlit_app/Dockerfile ./streamlit_app

          docker run -d -p 8000:8000 --name house-predicter-api ${{vars.DOCKERHUB_USERNAME}}/house-predicter-api:$COMMIT_HASH
          for i in {1..10}; do
            if curl -s http://localhost:8000/health; then
              echo "FastAPI server is up!"
              break
            else
              echo "Waiting for FastAPI server..."
              sleep 5
            fi
          done
          docker logs house-predicter-api

      - name: Cleanup Docker Images and Containers
        run: |
          docker stop house-predicter-api
          docker rm house-predicter-api

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag ${{vars.DOCKERHUB_USERNAME}}/house-predicter-api:$COMMIT_HASH ${{vars.DOCKERHUB_USERNAME}}/house-predicter-api:latest
          docker tag ${{vars.DOCKERHUB_USERNAME}}/streamlitapp:$COMMIT_HASH ${{vars.DOCKERHUB_USERNAME}}/streamlitapp:latest
          docker push ${{vars.DOCKERHUB_USERNAME}}/house-predicter-api:${COMMIT_HASH}
          docker push ${{vars.DOCKERHUB_USERNAME}}/streamlitapp:${COMMIT_HASH}
          docker push ${{vars.DOCKERHUB_USERNAME}}/house-predicter-api:latest 
          docker push ${{vars.DOCKERHUB_USERNAME}}/streamlitapp:latest

      